name: Build and Release

on:
  push:
    tags:
      - "v*"   # roda quando criar tag tipo v0.1.0
  workflow_dispatch: # também pode rodar manual

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build project
        run: cargo build --release

      # Linux
      - name: Package binary (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir artifacts
          tar -czvf artifacts/rustpass-linux-x86_64.tar.gz -C target/release rustpass

      # macOS
      - name: Package binary (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir artifacts
          tar -czvf artifacts/rustpass-macos-x86_64.tar.gz -C target/release rustpass

      # Windows
      - name: Package binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir artifacts
          powershell Compress-Archive -Path target/release/rustpass.exe -DestinationPath artifacts/rustpass-windows-x86_64.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustpass-${{ matrix.os }}
          path: artifacts/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
