name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  dist:
    name: Build and Package (cargo-dist)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-dist
        run: cargo install cargo-dist --locked
      - name: Build and Package
        run: cargo dist --no-confirm --tag ${{ github.ref_name }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustpass-dist
          path: dist/
      - name: Publish Release
        uses: taiki-e/upload-release-action@v1
        with:
          artifacts: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
