name: Build and Release

on:
  push:
    tags:
      - "v*"   # roda quando criar tag tipo v0.1.0
  workflow_dispatch: # também pode rodar manual

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build project
        run: cargo build --release

      - name: Package binary
        run: |
          mkdir artifacts
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            tar -czvf artifacts/rustpass-linux-x86_64.tar.gz -C target/release rustpass
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            tar -czvf artifacts/rustpass-macos-x86_64.tar.gz -C target/release rustpass
          else
            powershell Compress-Archive -Path target/release/rustpass.exe -DestinationPath artifacts/rustpass-windows-x86_64.zip
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustpass-${{ runner.os }}
          path: artifacts/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
